# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-18 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_user_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(default=None, related_name='_user_friends_+', to='app.User'),
        ),
    ]
