# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-20 07:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180518_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
