# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-20 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20180520_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='friends',
            field=models.ManyToManyField(to='app.Users'),
        ),
    ]
