# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-20 08:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20180520_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Users'),
        ),
        migrations.AlterField(
            model_name='users',
            name='about',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='users',
            name='friends',
            field=models.ManyToManyField(default=models.CharField(default='', max_length=50), related_name='_users_friends_+', to='app.Users'),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
