# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-20 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20180520_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='friends',
            field=models.ManyToManyField(default=None, related_name='_users_friends_+', to='app.Users'),
        ),
    ]
